### ISSUE TITLE
Invalid node reference when running EuropaMisson.plx

### ISSUE THREAD

**Issue by oceank** [nasa/ow_autonomy#28]
### Problem Description:
When launching autonomy module with the EuropaMission.plx, it complains "no node named SamplesOK reachable from node DumpCollectAnalyze". For detailed log, please refer the section of Logs at the bottom.

### System Info:
Use a physical machine but not a virtual machine
OS: Ubuntu 18.04.1
Linux Kernel: 5.4.0-65-generic
ROS: melodic
Gazebo: 9.16
PLEXIL: releases/plexil-4, commit 65f74037 with the fix of the "safe name" issue.
OW_Simulator: release 7 (commit ae5afc8, three commits after tag: v7.0.1)
OW_Autonomy: release 7 (tag: v7.0.1)

### Expected Behavior:
The autonomy node will be initialized successfully and start interacting with the workspace of Europa Mission.

### Observed Behavior:
The launch of the autonomy node fails due to the invalid node reference error.

### Steps to Reproduced the issue:

1. Launch Europa Mission workspace:
> (enter the ocean water workspace which has 'build' and 'devel' folders created by 'catkin build')
> source devel/setup.bash
> roslaunch ow europa_terminator.launch

2. Launch the autonomy node in another terminal
> (enter the ocean water workspace which has 'build' and 'devel' folders created by 'catkin build')
> source devel/setup.bash
> roslaunch ow_autonomy autonomy_node.launch plan:=EuropaMission.plx

### Logs: Launching autonomy module with EuropaMission.plx

```
[ INFO] [1614199818.775501354]: Waiting for action servers...
[ INFO] [1614199819.411776094, 1916524848.122499943]: Action servers available.
[ INFO] [1614199829.431530068, 1916524858.122499943]: Running plan EuropaMission.plx
ERROR: /home/jsu/ow_ws/src/ow_autonomy/src/plans/EuropaMission.ple:159:24: Invalid node reference: No node named SamplesOK reachable from node DumpCollectAnalyze
ExecApplication::addPlan: Plan parser error: 
```

**Comment by kmdalal** [comment]
This problem is fixed in Release 8, coming soon!

**Comment by kmdalal** [comment]
Thanks again for the detailed report, @oceank.  This issue is resolved.
