### ISSUE TITLE
About adding a ROS message type for autonomy node

### ISSUE THREAD

**Issue by oceank** [nasa/ow_autonomy#44]
What is the convention to add a customized ROS message type for autonomy node if the ROS message type is not for an arm operation? Is it suggested to directly add the message type in ow_autonomy code base? Thanks!

I see that several ROS message types are added in ow_simulator for arm operations and then used in autonomy node by including their automatically generated header files, e.g. ow_lander/Grind.h.

**Comment by kmdalal** [comment]
In general, if you'd like to extend ow_autonomy for the OceanWATERS user community, feel free to add anything to it and submit a pull request for addition to the open source.

So yes, to define new messages in ow_autonomy, add a 'msg' directory with the .msg files you need.  If you define msg/Foo.msg, when you build the package there will be a ow_autonomy/Foo.h to include, and you can define a ow_autonomy::Foo object.  There are tutorials for this online, e.g. https://wiki.ros.org/ROS/Tutorials/CreatingMsgAndSrv#Creating_a_msg

If this is work you want to keep separate from the general user community, then I'll suggest _forking_ the ow_autonomy repository and working with the forked version, making whatever changes you need.

**Comment by oceank** [comment]
> In general, if you'd like to extend ow_autonomy for the OceanWATERS user community, feel free to add anything to it and submit a pull request for addition to the open source.
> 
> So yes, to define new messages in ow_autonomy, add a 'msg' directory with the .msg files you need. If you define msg/Foo.msg, when you build the package there will be a ow_autonomy/Foo.h to include, and you can define a ow_autonomy::Foo object. There are tutorials for this online, e.g. https://wiki.ros.org/ROS/Tutorials/CreatingMsgAndSrv#Creating_a_msg
> 
> If this is work you want to keep separate from the general user community, then I'll suggest _forking_ the ow_autonomy repository and working with the forked version, making whatever changes you need.

Thank you for pointing out the tutorial of adding a new message type in ROS. It is really helpful.

We have forked OW repos and will submit pull requests when the extension is good for OceanWATERS user community as you suggested.

**Comment by kmdalal** [comment]
@oceank , do you need any more assistance with this issue?  Can it be closed?

**Comment by oceank** [comment]
> @oceank , do you need any more assistance with this issue? Can it be closed?

@kmdalal I am good now. Let's close this issue. Thanks!
