### ISSUE TITLE
OwlatTestSequence6.plp plan runs into a Kinematics failure [melodic-devel branch]

### ISSUE THREAD

**Issue by oceank** [nasa/ow_autonomy#72]
**Issue description:** 
After starting OWLAT, adding and sending OwlatTestSequence6 plan through the GUI leads to a Kinematics failure when executing ARM_MOVE_CARTESIAN action. ARM_MOVE_CARTESIAN action is issued in the PLEXIL library plan, OwlatPositionArm, and OwlatPositionArm is called in the PLEXIL plan, OwlatTestSequence6.

**The detailed output from the terminal launching owlat:**

> 0.000879113 DIAGNOSTIC: Initializing...
> 46.877614480 [ROS] DIAGNOSTIC: Command invoke 140586963209488 ARM_SET_TOOL
> 46.877662781 [ROS] DIAGNOSTIC: Command 140586963209488 ARM_SET_TOOL successful
> 46.878441616 [ROS] DIAGNOSTIC: Command invoke 140586493473120 ARM_MOVE_CARTESIAN
> 46.879563105 [ROS] ERROR: Command 140586493473120 **ARM_MOVE_CARTESIAN rejected: Kinematics Failure**: Could not resolve      0.14746 -2.51306e-09     0.182195 0.844589 4.72822e-09 0.535416 -6.17792e-09 from -1.61149e-08 -1.99 -1.28526e-09 3.12 4.24095e-10 5.68735e-09 -2.05927e-10

**Cause & Fix:**
The error above could be fixed by adding a call to the arm unstow operation before the call to the arm positioning operation, as shown below. And then compile OwlatTestSequence6.plp. The root cause might be that the ROS action, ARM_MOVE_CARTESIAN, has some requirements on the starting position of the arm while the stowed position of the arm does not satisfied the requirement.

> [A fix to OwlatTestSequence6.plp]
>  31   // gets arm into position
>  32   log_info("Unstowing arm with ARM_UNSTOW.");
>  33   **LibraryCall OwlatUnstow();**
>  34   LibraryCall OwlatPositionArm();

**Comment by kmdalal** [comment]
Sorry for the very slow response on this, @oceank, but I reproduced this problem in ROS Noetic and have implemented your suggested fix.  (I also added the unstow in all other test sequences).  I'm having a new error with this sequence (below).  If you can reproduce it we'll leave this issue open.

```
386.957086294 STDERR [LOG]: [ERROR]: Service call failed: service [/CmdStep] responded with an error: Problem with integration at t=288
.51,  cvode status=-3 (Error in DIntegratorCvode::lastStatus(): Error test failures occured too many times (ERR_FAILURE))               
386.957103786 STDERR [LOG]:  
386.957115679 STDERR [LOG]: [ERROR]: Service call failed: service [/CmdPrescribeJointAngles] responded with an error: Simulation::lockO
bject can only be called in the INITIALIZING or READY simulation phase, and not in the current SimulationPhase_WITHIN_INTEGRATION_STEP 
phase.                                                                                                                                  
386.957122959 STDERR [LOG]:  
386.957197045 ERROR [DARTS]: failed to send CmdPrescribeJointAngles 
386.957272123 ERROR: FaultProtection: Fault! ARM_GOAL_ERROR 
386.957343888 ERROR [ROS]: Command TASK_DROPOFF 140225795646688 Failure could not complete Dropoff Arm violated safety limits
```

**Comment by oceank** [comment]
> 

Hi, @kmdalal, I can reproduce the error you encountered when executing OwlatTestSequence6.plp using the most recent commits of noetic-devel branches:
ow_simulator: https://github.com/nasa/ow_simulator/commit/0a6f5ba1f34802b50630478f2e517be918924394
ow_autonomy: d270f884b7a9978a599d89b9cab8cd4ba08dbec5

Below is the error log I observed.

> 106.653094880 DIAGNOSTIC [TASK]: dropoff entering Hover
> 109.981115636 DIAGNOSTIC [TASK]: dropoff entering Dropoff
> 174.690832326 ERROR [DARTS]: Failed to step DARTS clock!
> 174.690847629 ERROR: FaultProtection: Fault! ARM_EXECUTION_ERROR
> 174.690871413 ERROR: FaultProtection: Fault! DARTS_INTERNAL_ERROR
> 174.691880991 ERROR [DARTS]: failed to send CmdPrescribeJointAngles
> 174.742564769 STDERR [LOG]: [ERROR] [1652844929.605094932]: Service call failed: service [/CmdStep] responded with an error: Problem with integration at t=113.51,  cvode status=-3 (Error in DIntegratorCvode::lastStatus(): Error test failures occured too many times (ERR_FAILURE))
> 174.742584522 STDERR [LOG]: 
> 174.742589822 ERROR: FaultProtection: Fault! ARM_GOAL_ERROR
> 174.742592597 STDERR [LOG]: [ERROR] [1652844929.606626004]: Service call failed: service [/CmdPrescribeJointAngles] responded with an error: Simulation::lockObject can only be called in the INITIALIZING or READY simulation phase, and not in the current SimulationPhase_WITHIN_INTEGRATION_STEP phase.
> 174.742606138 STDERR [LOG]: 
> 174.742724121 ERROR [ROS]: Command TASK_DROPOFF 139794679562416 Failure could not complete Dropoff Arm violated safety limits

**Comment by kmdalal** [comment]
Thanks for testing, @oceank !  I'll include investigating these errors in our task of checking and updating all the OWLAT test sequences, as others have issues, too.  We can leave this issue open until this specific sequence is fixed.

**Comment by kmdalal** [comment]
This problem was fixed earlier this summer, on the noetic-devel branch.
