### ISSUE TITLE
build failure due to "not declared function send_ack_once()" [noetic-devel branch]

### ISSUE THREAD

**Issue by oceank** [nasa/ow_autonomy#80]
Description: when building ow_plexil package (noetic-devel branch) for OWLAT, it complains the following error.

> Errors     << ow_plexil:make /home/sonam/oceanwater_ws_noetic/logs/ow_plexil/build.make.010.log 
> /home/sonam/oceanwater_ws_noetic/src/ow_autonomy/ow_plexil/src/plexil-adapter/OwlatAdapter.cpp: In function ‘void owlat_arm_move_cartesian(PLEXIL::Command*, PLEXIL::AdapterExecInterface*)’:
> /home/sonam/oceanwater_ws_noetic/src/ow_autonomy/ow_plexil/src/plexil-adapter/OwlatAdapter.cpp:64:3: error: ‘send_ack_once’ was not declared in this scope
>    64 |   send_ack_once(*cr);
>       |   ^~~~~~~~~~~~~
> make[2]: *** [src/plexil-adapter/CMakeFiles/ow_adapter.dir/build.make:193: src/plexil-adapter/CMakeFiles/ow_adapter.dir/OwlatAdapter.cpp.o] Error 1

Reproduce Stes:

1. Install new version of OWLAT
2. setup and build ow_simulator (noetic-devel branch)
3. comment out code related to shear bevameter in ow_autonomy (Due to #79)
4. build ow_plexil with the option -DOWLAT=ON for the OWLAT

Cause Discovery:
After comparing with the master branch of ow_autonomy, we find that send_ack_once() is intended to be replaced by acknowledge_command_sent() in adapter_support.h. While there are some left calls to send_ack_once(), which are not replaced yet.

Solution:
replace send_ack_once() with acknowledge_command_sent()

**Comment by kmdalal** [comment]
Thanks for the report @oceank .  I'll admit you're a step ahead of us.  We have not yet gotten OWLAT on our systems due to a problem associated with the default Python version being 2 on our systems.  I hope to have this problem resolved as early as tomorrow, and can than reproduce and fix your problem.   Please use the workaround you've found in the meantime - it is sound.

**Comment by kmdalal** [comment]
Problem fixed, as suggested, on noetic-devel.
